// This file is @generated by prost-build.
/// A simple Employee message
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Employee {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub address: ::prost::alloc::string::String,
    /// array
    #[prost(string, repeated, tag = "4")]
    pub social_media: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// map
    #[prost(map = "string, string", tag = "5")]
    pub accounts: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
